# Generated by Django 3.2.19 on 2023-06-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_if_active_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
